# Generated by Django 4.2 on 2026-01-04 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_id', models.UUIDField()),
                ('house_id', models.UUIDField()),
                ('reason', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'listing_reports',
            },
        ),
        migrations.CreateModel(
            name='RentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicant_id', models.UUIDField()),
                ('house_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rent_requests',
            },
        ),
        migrations.AddIndex(
            model_name='rentrequest',
            index=models.Index(fields=['applicant_id'], name='rent_reques_applica_2f5a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='rentrequest',
            index=models.Index(fields=['house_id'], name='rent_reques_house_i_361ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='rentrequest',
            index=models.Index(fields=['status'], name='rent_reques_status_82fad8_idx'),
        ),
        migrations.AddIndex(
            model_name='listingreport',
            index=models.Index(fields=['reporter_id'], name='listing_rep_reporte_232523_idx'),
        ),
        migrations.AddIndex(
            model_name='listingreport',
            index=models.Index(fields=['house_id'], name='listing_rep_house_i_f4ff86_idx'),
        ),
        migrations.AddIndex(
            model_name='listingreport',
            index=models.Index(fields=['status'], name='listing_rep_status_e85402_idx'),
        ),
    ]
