# Generated by Django 4.2 on 2026-06-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banlog',
            new_name='app_banlog_user_id_75c5de_idx',
            old_name='admin_servi_user_id_2ae3fe_idx',
        ),
        migrations.RenameIndex(
            model_name='banlog',
            new_name='app_banlog_admin_i_70f357_idx',
            old_name='admin_servi_admin_i_b9755c_idx',
        ),
        migrations.RenameIndex(
            model_name='banlog',
            new_name='app_banlog_created_0acdee_idx',
            old_name='admin_servi_created_19f535_idx',
        ),
        migrations.RenameIndex(
            model_name='houseratinglog',
            new_name='app_housera_house_i_d82abb_idx',
            old_name='admin_servi_house_i_fa0874_idx',
        ),
        migrations.RenameIndex(
            model_name='houseratinglog',
            new_name='app_housera_admin_i_0e5253_idx',
            old_name='admin_servi_admin_i_9abd45_idx',
        ),
        migrations.RenameIndex(
            model_name='houseratinglog',
            new_name='app_housera_created_a1a102_idx',
            old_name='admin_servi_created_42fb54_idx',
        ),
    ]
