# Generated by Django 5.2.8 on 2026-01-04 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(null=True)),
                ('admin_id', models.UUIDField(null=True)),
                ('action', models.CharField(choices=[('BAN', 'Ban'), ('UNBAN', 'Unban')], max_length=5)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='admin_servi_user_id_2ae3fe_idx'), models.Index(fields=['admin_id', 'created_at'], name='admin_servi_admin_i_b9755c_idx'), models.Index(fields=['created_at'], name='admin_servi_created_19f535_idx')],
            },
        ),
        migrations.CreateModel(
            name='HouseRatingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('house_id', models.UUIDField(null=True)),
                ('admin_id', models.UUIDField(null=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('category', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['house_id', 'created_at'], name='admin_servi_house_i_fa0874_idx'), models.Index(fields=['admin_id', 'created_at'], name='admin_servi_admin_i_9abd45_idx'), models.Index(fields=['created_at'], name='admin_servi_created_42fb54_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_id', models.UUIDField()),
                ('house_id', models.UUIDField(null=True)),
                ('reporter_id', models.UUIDField(null=True)),
                ('admin_id', models.UUIDField(null=True)),
                ('action', models.CharField(choices=[('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'report_logs',
                'indexes': [models.Index(fields=['report_id', 'created_at'], name='report_logs_report__919afe_idx'), models.Index(fields=['admin_id', 'created_at'], name='report_logs_admin_i_11fa64_idx'), models.Index(fields=['created_at'], name='report_logs_created_dda36f_idx')],
            },
        ),
    ]
